### ISSUE TITLE
Issue - Piwik is not initialized

### ISSUE THREAD

**Issue by afavata** [fnogatz/magento2-matomo#12] opened 2017-02-23 14:14 UTC
Hello, 

I installed the module Piwik for Magento 2 and configured. Looking to the browser console I'm gathering many issue regarding Piwik like:

_paq.push() was used but Piwik tracker was not initialized before the piwik.js file was loaded. Make sure to configure the tracker via _paq.push before loading piwik.js. Alternatively, you can create a tracker via Piwik.addTracker() manually and then use _paq.push but it may not fully work as tracker methods may not be executed in the correct order. Array[2]0: "setSiteId"1: 1length: 2__proto__: Array[0]
push @ piwik.js:70
pushAction @ tracker.js:202
(anonymous) @ tracker.js:194
_.each._.forEach @ underscore.js:145
pushAction @ tracker.js:193
initialize @ tracker.js:239
(anonymous) @ main.js:30
execCb @ require.js:1650
check @ require.js:866
(anonymous) @ require.js:1113
(anonymous) @ require.js:132
(anonymous) @ require.js:1156
each @ require.js:57
emit @ require.js:1155
check @ require.js:917
(anonymous) @ require.js:1113
(anonymous) @ require.js:132
(anonymous) @ require.js:1156
each @ require.js:57
emit @ require.js:1155
check @ require.js:917
(anonymous) @ require.js:1113
(anonymous) @ require.js:132
(anonymous) @ require.js:1156
each @ require.js:57
emit @ require.js:1155
check @ require.js:917
(anonymous) @ require.js:1113
(anonymous) @ require.js:132
(anonymous) @ require.js:1156
each @ require.js:57
emit @ require.js:1155
check @ require.js:917
enable @ require.js:1143
init @ require.js:774
callGetModule @ require.js:1170
completeLoad @ require.js:1544
onScriptLoad @ require.js:1671

Can you help me?! 

Thanks

**Comment by henkelund** [comment] 2017-02-23 14:31
This is most likely a duplicate of #11.

It will be fixed in the next release but if you don't wan't to wait for it you can try the `1.3.0` branch (`composer require henhed/module-piwik:1.3.0.x-dev`)

**Comment by afavata** [comment] 2017-02-23 16:09
Thank you for your prompt reply.... I will temporarily update to branch version 1.3.0, while waiting for the official release. 
Can you please send a comment as soon as new version is released

Thanks

**Comment by henkelund** [comment] 2017-02-24 08:15
No problem, I hope it fixes your problem. If you [watch](https://github.com/henkelund/magento2-henhed-piwik/subscription) this repository, I'm pretty sure you'll get a notification when the next release happens.

**Closed as completed by henkelund** 2017-02-24 08:15 UTC
Labels: duplicate

**Comment by henkelund** [comment] 2017-03-03 08:10
@afavata 1.3.0 is released
